/*
 * Generated by TKLGEN - VersionNov 27 2015
 * Copyright (C) 2013, Thiago Adams (thiago.adams@gmail.com)
 * www.thradams.com
 *
 */
#ifndef CPPLEX_H
#define CPPLEX_H



typedef enum 
{
    TKEXCLAMATION_MARK,
    TKQUOTATION_MARK,
    TKDOLLAR_SIGN,
    TKPERCENT_SIGN,
    TKAMPERSAND,
    TKAPOSTROPHE,
    TKLEFT_PARENTHESIS,
    TKRIGHT_PARENTHESIS,
    TKASTERISK,
    TKPLUS_SIGN,
    TKCOMMA,
    TKHYPHEN_MINUS,
    TKFULL_STOP,
    TKSOLIDUS,
    TKCOLON,
    TKSEMICOLON,
    TKLESS_THAN_SIGN,
    TKEQUALS_SIGN,
    TKGREATER_THAN_SIGN,
    TKQUESTION_MARK,
    TKCOMMERCIAL_AT,
    TKLEFT_SQUARE_BRACKET,
    TKREVERSE_SOLIDUS,
    TKRIGHT_SQUARE_BRACKET,
    TKCIRCUMFLEX_ACCENT,
    TKLOW_LINE,
    TKGRAVE_ACCENT,
    TKLEFT_CURLY_BRACKET,
    TKVERTICAL_LINE,
    TKRIGHT_CURLY_BRACKET,
    TKTILL,
    TKNUMBER_SIGN,
    TKTKNOWIKI_BLOCK_CLOSE,
    TKLINECOMMENT,
    TKCOMMENT,
    TKCHAR,
    TKSTRING,
    TKBlanks,
    TKBreakLine,
    TKNotBreakLine,
    TKEndMark,
    TKNumber,
    TKIdentifier,
} Cpp_Tokens;

const char* Cpp_Tokens_ToString(Cpp_Tokens e);


int Cpp_GetNext(int state, wchar_t ch);
int Cpp_GetTokenFromState(int state, Cpp_Tokens* tk);
int Cpp_IsInterleave(Cpp_Tokens tk);

#endif
