/*
 * Generated by TKLGEN - VersionNov 27 2015
 * Copyright (C) 2013, Thiago Adams (thiago.adams@gmail.com)
 * www.thradams.com
 *
 */
#ifndef CPP_H
#define CPP_H


#include "Result.h"
#include "Cpp.h"

typedef enum 
{
Cpp_OnError
}Cpp_Actions;

Result Cpp_Main(Cpp_Context* ctx);
const char* Cpp_Actions_Text(Cpp_Actions e);



#endif
