/*
 * Generated by TKLGEN - VersionNov 27 2015
 * Copyright (C) 2013, Thiago Adams (thiago.adams@gmail.com)
 * www.thradams.com
 *
 */

#include "stdafx.h"
#include <assert.h>

#include "CppLex.h"
#include "CppParser.h"




//
const char* Cpp_Actions_Text(Cpp_Actions e)
{
    switch(e)
    {
    }
    return "";
};

/*forward declarations*/ 
Result Cpp_Main( Cpp_Context* ctx);





#define _CHECK if (result == RESULT_OK || result == RESULT_EMPTY) result = 



Result Cpp_Main( Cpp_Context* ctx)
{
    Result result = RESULT_OK;
    Cpp_Tokens token = ctx->token; 

    if (token == TKIdentifier)
    {
        /*Main => Identifier */
        _CHECK Cpp_Match(ctx, TKIdentifier);
    }
    else
    {
        Cpp_OnAction(ctx, Cpp_OnError); 
        return RESULT_FAIL;
    }

    return result;
}

