/*
 * Generated by TKLGEN - VersionNov 27 2015
 * Copyright (C) 2013, Thiago Adams (thiago.adams@gmail.com)
 * www.thradams.com
 *
 */
#ifndef MARKUP_H
#define MARKUP_H


#include "Result.h"
#include "Markup.h"

typedef enum 
{
Markup_OnError
}Markup_Actions;

Result Markup_Main(Markup_Context* ctx);
const char* Markup_Actions_Text(Markup_Actions e);



#endif
