/*
 * Generated by TKLGEN - VersionNov 27 2015
 * Copyright (C) 2013, Thiago Adams (thiago.adams@gmail.com)
 * www.thradams.com
 *
 */

#include "stdafx.h"
#include <assert.h>

#include "MarkupLex.h"
#include "MarkupParser.h"




//
const char* Markup_Actions_Text(Markup_Actions e)
{
    switch(e)
    {
    }
    return "";
};

/*forward declarations*/ 
Result Markup_Main( Markup_Context* ctx);





#define _CHECK if (result == RESULT_OK || result == RESULT_EMPTY) result = 



Result Markup_Main( Markup_Context* ctx)
{
    Result result = RESULT_OK;
    Markup_Tokens token = ctx->token; 

    if (token == TKImage)
    {
        /*Main => Image */
        _CHECK Markup_Match(ctx, TKImage);
    }
    else
    {
        Markup_OnAction(ctx, Markup_OnError); 
        return RESULT_FAIL;
    }

    return result;
}

